services:
  - type: web
    name: stream-views
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m src.main
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: YOUTUBE_API_KEY
        sync: false
      - key: PORT
        value: 10000 