services:
  - type: web
    name: stream-views
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python APP/src/main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: YOUTUBE_API_KEY
        sync: false