services:
  - type: web
    name: stream-views
    env: python
    buildCommand: |
      echo "=== Current Directory ==="
      pwd
      echo "=== Directory Contents ==="
      ls -la
      echo "=== Installing Requirements ==="
      pip install -r requirements.txt
    startCommand: |
      echo "=== Starting Application ==="
      echo "=== Current Directory ==="
      pwd
      echo "=== Directory Contents ==="
      ls -la
      echo "=== Python Version ==="
      python --version
      echo "=== Python Path ==="
      python -c "import sys; print('\n'.join(sys.path))"
      echo "=== Trying to run main.py ==="
      find . -name "main.py"
      echo "=== Running main.py ==="
      python src/main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: YOUTUBE_API_KEY
        sync: false
      - key: PORT
        value: 10000 