services:
  - type: web
    name: stream-views
    env: python
    buildCommand: |
      echo "=== Build Phase ==="
      echo "Current directory: $(pwd)"
      echo "Directory contents:"
      ls -la
      echo "Installing requirements..."
      pip install -r requirements.txt
    startCommand: cd APP && python wsgi.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: YOUTUBE_API_KEY
        sync: false
      - key: PORT
        value: 10000 