services:
  - type: web
    name: stream-views
    env: python
    buildCommand: |
      cd /opt/render/project/src/APP
      pip install -r requirements.txt
    startCommand: |
      cd /opt/render/project/src/APP
      PYTHONPATH=/opt/render/project/src/APP python src/main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: YOUTUBE_API_KEY
        sync: false
      - key: PORT
        value: 10000 