services:
  - type: web
    name: stream-views
    env: python
    buildCommand: |
      echo "=== Build Phase ==="
      echo "Current directory: $(pwd)"
      echo "Directory contents:"
      ls -la
      echo "Installing requirements..."
      pip install -r requirements.txt
    startCommand: |
      echo "=== Start Phase ==="
      echo "Current directory: $(pwd)"
      echo "Directory contents:"
      ls -la
      echo "Creating start script..."
      cat > start.sh << 'EOL'
      #!/bin/bash
      echo "=== Start Script ==="
      echo "Current directory: $(pwd)"
      echo "Directory contents:"
      ls -la
      echo "Searching for main.py..."
      find . -name "main.py"
      echo "Python path:"
      python -c "import sys; print('\n'.join(sys.path))"
      echo "Running main.py..."
      if [ -f "src/main.py" ]; then
          echo "Found main.py in src directory"
          python src/main.py
      elif [ -f "APP/src/main.py" ]; then
          echo "Found main.py in APP/src directory"
          python APP/src/main.py
      else
          echo "main.py not found in expected locations"
          exit 1
      fi
      EOL
      chmod +x start.sh
      ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: YOUTUBE_API_KEY
        sync: false
      - key: PORT
        value: 10000 